<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>robot</string>
	</array>
	<key>name</key>
	<string>Robot Framework syntax highlighting.</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>comment</key>
			<string>Robot Framework numbers, like ${1} or ${12.3}</string>
			<key>match</key>
			<string>\$\{(\d+|\d+\.\d*|0[bB][01]+|0[oO][0-7]+|0[xX][0-9a-fA-F]+)\}</string>
			<key>name</key>
			<string>constant.numeric.robot</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Robot Framework environment variable, like %{USER}</string>
			<key>match</key>
			<string>(?i)(%\{[\w|\s]+\})</string>
			<key>name</key>
			<string>variable.parameter.robot</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>((?&lt;!\\)|(?&lt;=\\\\))[$&amp;]{</string>
			<key>comment</key>
			<string>Robot Framework scalar and dictionary variables</string>
			<key>end</key>
			<string>\}</string>
			<key>name</key>
			<string>entity.name.class</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>((?&lt;!\\)(@{)|(?&lt;=\\\\)(@{))</string>
			<key>comment</key>
			<string>Robot Framework list variables</string>
			<key>end</key>
			<string>(}\[.+])|(})</string>
			<key>name</key>
			<string>entity.name.class</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Robot Framework data tables</string>
			<key>match</key>
			<string>(?i)^(\|\s*)?(\*{1,3} ?)(settings?|variables?|keywords?|test cases?)( ?\*{1,3})?(\s*\|)?</string>
			<key>name</key>
			<string>string.robot.header</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(?i)(^\|\s*)?\[?Documentation\]?\s+</string>
			<key>comment</key>
			<string>Test case, keyword and settings table documentation</string>
			<key>end</key>
			<string>^(?!\s*+\.\.\.)</string>
			<key>name</key>
			<string>comment</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(^| {2,}|\t|\\| {1,})(?&lt;!\\\\)#</string>
			<key>comment</key>
			<string>Comment character</string>
			<key>end</key>
			<string>$</string>
			<key>name</key>
			<string>comment</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Tests case and keyword settings</string>
			<key>match</key>
			<string>(?i)\s+\[(Tags|Setup|Teardown|Template|Timeout|Arguments|Return)\]</string>
			<key>name</key>
			<string>storage.type</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Settings table settings, like Library</string>
			<key>match</key>
			<string>(?i)^(\|\s*)?(Library|Resource|Test Timeout|Test Template|Test Teardown|Test Setup|Default Tags|Force Tags|Metadata|Variables|Suite Setup|Suite Teardown)(?:(  )|( \| ))</string>
			<key>name</key>
			<string>constant.language</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>^(\|\s+)?(?!^\.{3})(?![\|$&amp;])\S+</string>
			<key>comment</key>
			<string>Keywords and test cases</string>
			<key>end</key>
			<string>($|\||\s{2,})</string>
			<key>name</key>
			<string>keyword.control.robot</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>BDD keywords</string>
			<key>match</key>
			<string>(?i)^\s+(Given|When|and|but|Then)</string>
			<key>name</key>
			<string>string.robot.bdd</string>
		</dict>	</array>
	<key>scopeName</key>
	<string>source.robot</string>
	<key>uuid</key>
	<string>23650265-9dfb-4d5f-9ed0-0928ba59a796</string>
</dict>
</plist>
