# Default global variables from Robot Framework
RF_VARS = ['${/}',
           '${:}',
           '${\\n}',
           '${DEBUG_FILE}',
           '${EXECDIR}',
           '${False}',
           '${LOG_FILE}',
           '${LOG_LEVEL}',
           '${None}',
           '${null}',
           '${OUTPUT_DIR}',
           '${OUTPUT_FILE}',
           '${PREV_TEST_MESSAGE}',
           '${PREV_TEST_NAME}',
           '${PREV_TEST_STATUS}',
           '${REPORT_FILE}',
           '${SPACE}',
           '${SUITE_DOCUMENTATION}',
           '${SUITE_NAME}',
           '${SUITE_SOURCE}',
           '${TEMPDIR}',
           '${TEST_DOCUMENTATION}',
           '${TEST_NAME}',
           '${True}',
           '&{SUITE_METADATA}',
           '@{TEST_TAGS}'
           ]
